# Generated by Django 4.2.26 on 2025-11-21 05:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('balance', models.IntegerField(verbose_name='残高')),
                ('source', models.CharField(choices=[('manual', '手動入力'), ('api', 'API取得')], default='manual', max_length=20, verbose_name='データソース')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
            ],
            options={
                'verbose_name': '口座残高',
                'verbose_name_plural': '口座残高',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, unique=True, verbose_name='年月')),
                ('salary', models.IntegerField(default=0, verbose_name='給与')),
                ('bonus', models.IntegerField(default=0, verbose_name='ボーナス')),
                ('food', models.IntegerField(default=0, verbose_name='食費')),
                ('rent', models.IntegerField(default=0, verbose_name='家賃')),
                ('lake', models.IntegerField(default=0, verbose_name='レイク返済')),
                ('credit', models.IntegerField(default=0, verbose_name='クレカ引落')),
                ('savings', models.IntegerField(default=0, verbose_name='定期預金')),
                ('loan', models.IntegerField(default=0, verbose_name='マネーアシスト返済')),
                ('utilities', models.IntegerField(default=0, verbose_name='光熱費')),
                ('transportation', models.IntegerField(default=0, verbose_name='交通費')),
                ('entertainment', models.IntegerField(default=0, verbose_name='娯楽費')),
                ('other', models.IntegerField(default=0, verbose_name='その他')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '月次計画',
                'verbose_name_plural': '月次計画',
                'ordering': ['year_month'],
            },
        ),
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_balance', models.IntegerField(default=0, help_text='シミュレーション開始時の口座残高', verbose_name='初期残高')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('simulation_months', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='シミュレーション期間（月）')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'シミュレーション設定',
                'verbose_name_plural': 'シミュレーション設定',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('event_type', models.CharField(choices=[('salary', '給与'), ('bonus', 'ボーナス'), ('food', '食費'), ('rent', '家賃'), ('lake', 'レイク返済'), ('credit', 'クレカ引落'), ('savings', '定期預金'), ('loan', 'マネーアシスト返済'), ('utilities', '光熱費'), ('transportation', '交通費'), ('entertainment', '娯楽費'), ('other', 'その他')], max_length=20, verbose_name='種類')),
                ('event_name', models.CharField(max_length=100, verbose_name='イベント名')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('balance_after', models.IntegerField(verbose_name='取引後残高')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget_app.monthlyplan', verbose_name='関連月')),
            ],
            options={
                'verbose_name': '取引イベント',
                'verbose_name_plural': '取引イベント',
                'ordering': ['date', 'id'],
            },
        ),
    ]
