# Generated by Django 4.2.26 on 2025-11-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='loan_borrowing',
            field=models.IntegerField(default=0, verbose_name='マネーアシスト借入'),
        ),
    ]
