# Generated by Django 4.2.26 on 2025-11-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_monthlyplan_loan_borrowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationconfig',
            name='savings_amount',
            field=models.IntegerField(default=0, help_text='毎月の定期預金額', verbose_name='定期預金額（円）'),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='savings_start_month',
            field=models.CharField(blank=True, help_text='定期預金を開始する年月', max_length=7, null=True, verbose_name='定期預金開始月（YYYY-MM）'),
        ),
    ]
