# Generated by Django 4.2.26 on 2025-11-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_simulationconfig_savings_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='credit2',
            field=models.IntegerField(default=0, verbose_name='クレカ引落2'),
        ),
    ]
