# Generated by Django 4.2.26 on 2025-11-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_monthlyplan_credit2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyplan',
            name='credit2',
            field=models.IntegerField(default=0, verbose_name='その他クレカ'),
        ),
    ]
