# Generated by Django 4.2.26 on 2025-11-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_alter_monthlyplan_credit2'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationconfig',
            name='default_salary',
            field=models.IntegerField(default=271919, help_text='月次計画作成時のデフォルト給与額', verbose_name='デフォルト給与（円）'),
        ),
    ]
