# Generated by Django 4.2.26 on 2025-11-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0006_simulationconfig_default_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, verbose_name='請求月（YYYY-MM）')),
                ('card_type', models.CharField(choices=[('main', 'クレカ'), ('other', 'その他クレカ')], max_length=10, verbose_name='カード種別')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='メモ')),
                ('amount', models.IntegerField(verbose_name='見積額（円）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'クレカ見積り',
                'verbose_name_plural': 'クレカ見積り',
                'ordering': ['year_month', 'card_type', '-created_at'],
            },
        ),
    ]
