# Generated by Django 4.2.26 on 2025-11-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0007_creditestimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationconfig',
            name='amazon_prime_default',
            field=models.IntegerField(default=600, help_text='デフォルトのAmazon Prime請求額', verbose_name='Amazon Prime（月額）'),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='apple_music_default',
            field=models.IntegerField(default=1980, help_text='デフォルトのApple Music請求額', verbose_name='Apple Music（月額）'),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='heroku_default',
            field=models.IntegerField(default=798, help_text='デフォルトのHeroku請求額', verbose_name='Heroku（月額）'),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='moneytree_default',
            field=models.IntegerField(default=360, help_text='デフォルトのMoneytree請求額', verbose_name='Moneytree（月額）'),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='ntt_default',
            field=models.IntegerField(default=5170, help_text='デフォルトのNTT請求額', verbose_name='NTT（月額）'),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='water_default',
            field=models.IntegerField(default=3806, help_text='デフォルトの水道料金（奇数月のみ反映）', verbose_name='水道（奇数月）'),
        ),
        migrations.AlterField(
            model_name='creditestimate',
            name='card_type',
            field=models.CharField(choices=[('view', 'VIEWカード'), ('rakuten', '楽天カード'), ('paypay', 'PayPayカード'), ('vermillion', 'VERMILLION CARD'), ('amazon', 'Amazonカード')], max_length=10, verbose_name='カード種別'),
        ),
    ]
