# Generated by Django 4.2.26 on 2025-11-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0008_simulationconfig_amazon_prime_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyplan',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='monthlyplan',
            name='credit2',
        ),
        migrations.RemoveField(
            model_name='monthlyplan',
            name='entertainment',
        ),
        migrations.RemoveField(
            model_name='monthlyplan',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='monthlyplan',
            name='utilities',
        ),
        migrations.RemoveField(
            model_name='simulationconfig',
            name='amazon_prime_default',
        ),
        migrations.RemoveField(
            model_name='simulationconfig',
            name='apple_music_default',
        ),
        migrations.RemoveField(
            model_name='simulationconfig',
            name='heroku_default',
        ),
        migrations.RemoveField(
            model_name='simulationconfig',
            name='moneytree_default',
        ),
        migrations.RemoveField(
            model_name='simulationconfig',
            name='ntt_default',
        ),
        migrations.RemoveField(
            model_name='simulationconfig',
            name='water_default',
        ),
        migrations.AddField(
            model_name='creditestimate',
            name='due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1〜31 の間で設定（任意）', null=True, verbose_name='請求日（任意）'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='amazon_card',
            field=models.IntegerField(default=0, verbose_name='Amazonカード'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='rakuten_paypay_card',
            field=models.IntegerField(default=0, verbose_name='楽天/PayPayカード'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='vermillion_card',
            field=models.IntegerField(default=0, verbose_name='VERMILLION CARD'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='view_card',
            field=models.IntegerField(default=0, verbose_name='VIEWカード'),
        ),
        migrations.AlterField(
            model_name='transactionevent',
            name='event_type',
            field=models.CharField(choices=[('salary', '給与'), ('bonus', 'ボーナス'), ('food', '食費'), ('rent', '家賃'), ('lake', 'レイク返済'), ('view_card', 'VIEWカード'), ('rakuten_paypay_card', '楽天/PayPayカード'), ('vermillion_card', 'VERMILLION CARD'), ('amazon_card', 'Amazonカード'), ('savings', '定期預金'), ('loan', 'マネーアシスト返済'), ('other', 'その他')], max_length=20, verbose_name='種類'),
        ),
    ]
