# Generated by Django 4.2.26 on 2025-11-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0009_remove_monthlyplan_credit_remove_monthlyplan_credit2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='キー')),
                ('label', models.CharField(max_length=100, verbose_name='項目名')),
                ('card_type', models.CharField(choices=[('view', 'VIEWカード'), ('rakuten', '楽天カード'), ('paypay', 'PayPayカード'), ('vermillion', 'VERMILLION CARD'), ('amazon', 'Amazonカード')], max_length=10, verbose_name='カード種別')),
                ('amount', models.IntegerField(default=0, verbose_name='金額（円）')),
            ],
            options={
                'verbose_name': '定期デフォルト',
                'verbose_name_plural': '定期デフォルト',
                'ordering': ['key'],
            },
        ),
    ]
