# Generated by Django 5.2.8 on 2025-11-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0011_split_rakuten_paypay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditestimate',
            name='due_day',
        ),
        migrations.AddField(
            model_name='creditestimate',
            name='due_date',
            field=models.DateField(blank=True, help_text='請求日をカレンダーから選択', null=True, verbose_name='請求日'),
        ),
        migrations.AddField(
            model_name='creditestimate',
            name='is_split_payment',
            field=models.BooleanField(default=False, verbose_name='分割2回払い'),
        ),
        migrations.AlterField(
            model_name='transactionevent',
            name='event_type',
            field=models.CharField(choices=[('salary', '給与'), ('bonus', 'ボーナス'), ('food', '食費'), ('rent', '家賃'), ('lake', 'レイク返済'), ('view_card', 'VIEWカード'), ('rakuten_card', '楽天カード'), ('paypay_card', 'PayPayカード'), ('vermillion_card', 'VERMILLION CARD'), ('amazon_card', 'Amazonカード'), ('savings', '定期預金'), ('loan', 'マネーアシスト返済'), ('other', 'その他')], max_length=20, verbose_name='種類'),
        ),
    ]
