# Generated by Django 5.2.8 on 2025-11-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0012_remove_creditestimate_due_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditestimate',
            name='is_bonus_payment',
            field=models.BooleanField(default=False, verbose_name='ボーナス払い'),
        ),
    ]
