# Generated by Django 5.2.8 on 2025-11-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0013_creditestimate_is_bonus_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationconfig',
            name='default_food',
            field=models.IntegerField(default=0, help_text='月次計画作成時のデフォルト食費', verbose_name='デフォルト食費（円）'),
        ),
    ]
