# Generated by Django 5.2.8 on 2025-11-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0014_simulationconfig_default_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='view_card_bonus',
            field=models.IntegerField(default=0, verbose_name='ボーナス払い'),
        ),
    ]
