# Generated by Django 5.2.8 on 2025-11-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0015_monthlyplan_amazon_card_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationconfig',
            name='savings_enabled',
            field=models.BooleanField(default=False, help_text='定期預金機能のオン/オフ', verbose_name='定期預金を有効化'),
        ),
    ]
