# Generated by Django 5.2.8 on 2025-11-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0016_simulationconfig_savings_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationconfig',
            name='default_view_card',
            field=models.IntegerField(default=50000, help_text='クレカ見積もりに毎月デフォルトで計上されるVIEWカードの金額', verbose_name='VIEWカードデフォルト利用額（円）'),
        ),
    ]
