# Generated by Django 5.2.8 on 2025-11-22 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0017_simulationconfig_default_view_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultChargeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='YYYY-MM形式', max_length=7, verbose_name='対象年月')),
                ('amount', models.PositiveIntegerField(verbose_name='上書き金額')),
                ('default', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='budget_app.creditdefault')),
            ],
            options={
                'verbose_name': '定期デフォルトの上書き',
                'verbose_name_plural': '定期デフォルトの上書き',
                'unique_together': {('default', 'year_month')},
            },
        ),
    ]
