# Generated by Django 5.2.8 on 2025-11-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0018_defaultchargeoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdefault',
            name='apply_odd_months_only',
            field=models.BooleanField(default=False, verbose_name='奇数月のみ適用'),
        ),
        migrations.AddField(
            model_name='creditdefault',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
    ]
