# Generated by Django 5.2.8 on 2025-11-24 10:19

from django.db import migrations


def clear_loan_repayments(apps, schema_editor):
    """既存のマネーアシスト返済データをクリア（自動管理に移行するため）"""
    MonthlyPlan = apps.get_model('budget_app', 'MonthlyPlan')
    MonthlyPlan.objects.all().update(loan=0)


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0019_creditdefault_apply_odd_months_only_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_loan_repayments, migrations.RunPython.noop),
    ]
