# Generated by Django 5.2.8 on 2025-11-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0020_clear_loan_repayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditestimate',
            name='split_payment_group',
            field=models.CharField(blank=True, help_text='同じ分割払いのペアを識別するID', max_length=50, null=True, verbose_name='分割払いグループID'),
        ),
        migrations.AddField(
            model_name='creditestimate',
            name='split_payment_part',
            field=models.IntegerField(blank=True, help_text='分割払いの場合、1 or 2', null=True, verbose_name='分割払い回数'),
        ),
    ]
