# Generated by Django 5.2.8 on 2025-11-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0022_migrate_split_payment_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='olive_card',
            field=models.IntegerField(default=0, verbose_name='Olive'),
        ),
        migrations.AlterField(
            model_name='creditdefault',
            name='card_type',
            field=models.CharField(choices=[('view', 'VIEWカード'), ('rakuten', '楽天カード'), ('paypay', 'PayPayカード'), ('vermillion', 'VERMILLION CARD'), ('amazon', 'Amazonカード'), ('olive', 'Olive')], max_length=10, verbose_name='カード種別'),
        ),
        migrations.AlterField(
            model_name='creditestimate',
            name='card_type',
            field=models.CharField(choices=[('view', 'VIEWカード'), ('rakuten', '楽天カード'), ('paypay', 'PayPayカード'), ('vermillion', 'VERMILLION CARD'), ('amazon', 'Amazonカード'), ('olive', 'Olive')], max_length=10, verbose_name='カード種別'),
        ),
    ]
