# Generated by Django 5.2.8 on 2025-11-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0023_monthlyplan_olive_card_alter_creditdefault_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='deductions',
            field=models.IntegerField(default=0, verbose_name='控除額'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='gross_salary',
            field=models.IntegerField(default=0, verbose_name='総支給額'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='net_salary',
            field=models.IntegerField(default=0, verbose_name='差引支給額'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='transportation',
            field=models.IntegerField(default=0, verbose_name='交通費'),
        ),
    ]
