# Generated by Django 5.2.8 on 2025-11-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0024_monthlyplan_deductions_monthlyplan_gross_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyplan',
            name='net_salary',
        ),
    ]
