# Generated by Django 5.2.8 on 2025-11-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0025_remove_monthlyplan_net_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultchargeoverride',
            name='card_type',
            field=models.CharField(blank=True, choices=[('view', 'VIEWカード'), ('rakuten', '楽天カード'), ('paypay', 'PayPayカード'), ('vermillion', 'VERMILLION CARD'), ('amazon', 'Amazonカード'), ('olive', 'Olive')], help_text='この月だけカード種別を変更する場合に指定', max_length=20, null=True, verbose_name='カード種別'),
        ),
    ]
