# Generated by Django 5.2.8 on 2025-11-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0026_defaultchargeoverride_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='bonus_deductions',
            field=models.IntegerField(default=0, verbose_name='ボーナス控除額'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='bonus_gross_salary',
            field=models.IntegerField(default=0, verbose_name='ボーナス総支給額'),
        ),
    ]
