# Generated by Django 5.2.8 on 2025-11-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0027_monthlyplan_bonus_deductions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdefault',
            name='is_split_payment',
            field=models.BooleanField(default=False, verbose_name='2回払い'),
        ),
    ]
