# Generated by Django 5.2.8 on 2025-11-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0028_creditdefault_is_split_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditdefault',
            name='is_split_payment',
        ),
    ]
