# Generated by Django 5.2.8 on 2025-11-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0029_remove_creditdefault_is_split_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultchargeoverride',
            name='is_split_payment',
            field=models.BooleanField(default=False, help_text='この月だけ2回払いにする場合にチェック', verbose_name='2回払い'),
        ),
    ]
