# Generated by Django 5.2.8 on 2025-12-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0037_fix_bonus_payment_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyplan',
            name='other',
            field=models.IntegerField(default=7700, verbose_name='ジム'),
        ),
        migrations.AlterField(
            model_name='simulationconfig',
            name='savings_amount',
            field=models.IntegerField(default=50000, help_text='毎月の定期預金額', verbose_name='定期預金額（円）'),
        ),
        migrations.AlterField(
            model_name='transactionevent',
            name='event_type',
            field=models.CharField(choices=[('salary', '給与'), ('bonus', 'ボーナス'), ('food', '食費'), ('rent', '家賃'), ('lake', 'レイク返済'), ('view_card', 'VIEWカード'), ('rakuten_card', '楽天カード'), ('paypay_card', 'PayPayカード'), ('vermillion_card', 'VERMILLION CARD'), ('amazon_card', 'Amazonカード'), ('savings', '定期預金'), ('loan', 'マネーアシスト返済'), ('other', 'ジム')], max_length=20, verbose_name='種類'),
        ),
    ]
