# Generated by Django 4.2.26 on 2025-12-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0038_change_other_default_to_7700'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='exclude_amazon_card',
            field=models.BooleanField(default=False, verbose_name='Amazonカード除外'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='exclude_olive_card',
            field=models.BooleanField(default=False, verbose_name='Olive除外'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='exclude_paypay_card',
            field=models.BooleanField(default=False, verbose_name='PayPayカード除外'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='exclude_rakuten_card',
            field=models.BooleanField(default=False, verbose_name='楽天カード除外'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='exclude_vermillion_card',
            field=models.BooleanField(default=False, verbose_name='VERMILLION除外'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='exclude_view_card',
            field=models.BooleanField(default=False, verbose_name='VIEWカード除外'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='exclude_view_card_bonus',
            field=models.BooleanField(default=False, verbose_name='VIEWボーナス払い除外'),
        ),
    ]
