# Generated by Django 5.2.8 on 2025-12-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0039_monthlyplan_exclude_amazon_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPlanDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='項目名')),
                ('amount', models.IntegerField(default=0, verbose_name='デフォルト金額（円）')),
                ('withdrawal_day', models.IntegerField(blank=True, help_text='1-31の数値。クレジットカードの場合は引き落とし日を設定', null=True, verbose_name='引き落とし日')),
                ('consider_holidays', models.BooleanField(default=False, help_text='引き落とし日が休日の場合、翌営業日に調整', verbose_name='休日を考慮')),
                ('closing_day', models.IntegerField(blank=True, help_text='クレジットカードの場合のみ設定。1-31の数値', null=True, verbose_name='締め日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': '月次計画デフォルト項目',
                'verbose_name_plural': '月次計画デフォルト項目',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='exclude_amazon_card',
            field=models.BooleanField(default=False, verbose_name='Amazonカード繰上げ返済'),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='exclude_olive_card',
            field=models.BooleanField(default=False, verbose_name='Olive繰上げ返済'),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='exclude_paypay_card',
            field=models.BooleanField(default=False, verbose_name='PayPayカード繰上げ返済'),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='exclude_rakuten_card',
            field=models.BooleanField(default=False, verbose_name='楽天カード繰上げ返済'),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='exclude_vermillion_card',
            field=models.BooleanField(default=False, verbose_name='VERMILLION繰上げ返済'),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='exclude_view_card',
            field=models.BooleanField(default=False, verbose_name='VIEWカード繰上げ返済'),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='exclude_view_card_bonus',
            field=models.BooleanField(default=False, verbose_name='VIEWボーナス払い繰上げ返済'),
        ),
    ]
