# Generated by Django 5.2.8 on 2025-12-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0040_monthlyplandefault_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplandefault',
            name='payment_type',
            field=models.CharField(choices=[('deposit', '振込'), ('withdrawal', '引き落とし')], default='withdrawal', help_text='振込または引き落とし', max_length=20, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='monthlyplandefault',
            name='consider_holidays',
            field=models.BooleanField(default=False, help_text='振込:休日なら直前の金曜、引落:休日なら翌営業日', verbose_name='休日を考慮'),
        ),
        migrations.AlterField(
            model_name='monthlyplandefault',
            name='withdrawal_day',
            field=models.IntegerField(blank=True, help_text='1-31の数値。引き落とし日または振込日を設定', null=True, verbose_name='引き落とし日/振込日'),
        ),
    ]
