# Generated by Django 5.2.8 on 2025-12-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0041_monthlyplandefault_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplandefault',
            name='is_end_of_month',
            field=models.BooleanField(default=False, help_text='チェックすると締め日が月末になります', verbose_name='締め日を月末にする'),
        ),
    ]
