# Generated by Django 5.2.8 on 2025-12-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0042_monthlyplandefault_is_end_of_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplandefault',
            name='is_withdrawal_end_of_month',
            field=models.BooleanField(default=False, help_text='チェックすると引き落とし日/振込日が月末になります', verbose_name='引き落とし日/振込日を月末にする'),
        ),
    ]
