# Generated by Django 5.2.8 on 2025-12-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0043_monthlyplandefault_is_withdrawal_end_of_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='exclusions',
            field=models.JSONField(default=dict, help_text="クレカ項目の繰上げ返済フラグ 例: {'view_card': True, 'rakuten_card': False}", verbose_name='繰上げ返済フラグ'),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='items',
            field=models.JSONField(default=dict, help_text="MonthlyPlanDefaultで定義された項目の金額を格納 例: {'salary': 271919, 'food': 50000}", verbose_name='計画項目'),
        ),
    ]
