# Generated by Django 5.2.8 on 2025-12-28 03:12

from django.db import migrations


def migrate_existing_data_to_json(apps, schema_editor):
    """既存の固定フィールドからJSONFieldにデータを移行"""
    MonthlyPlan = apps.get_model('budget_app', 'MonthlyPlan')

    # フィールドマッピング
    item_fields = [
        'salary', 'bonus', 'food', 'rent', 'lake',
        'view_card', 'view_card_bonus', 'rakuten_card', 'paypay_card',
        'vermillion_card', 'amazon_card', 'olive_card',
        'savings', 'loan', 'loan_borrowing', 'other',
        'gross_salary', 'deductions', 'transportation',
        'bonus_gross_salary', 'bonus_deductions'
    ]

    exclusion_fields = [
        'view_card', 'view_card_bonus', 'rakuten_card',
        'paypay_card', 'vermillion_card', 'amazon_card', 'olive_card'
    ]

    for plan in MonthlyPlan.objects.all():
        # items JSONFieldに移行
        items = {}
        for field in item_fields:
            value = getattr(plan, field, 0)
            if value != 0:  # 0以外の値のみ保存
                items[field] = value

        # exclusions JSONFieldに移行
        exclusions = {}
        for field in exclusion_fields:
            exclude_field = f'exclude_{field}'
            value = getattr(plan, exclude_field, False)
            if value:  # Trueの場合のみ保存
                exclusions[field] = value

        # JSONFieldを更新
        plan.items = items
        plan.exclusions = exclusions
        plan.save()


def reverse_migration(apps, schema_editor):
    """ロールバック時にJSONFieldから固定フィールドに戻す"""
    MonthlyPlan = apps.get_model('budget_app', 'MonthlyPlan')

    for plan in MonthlyPlan.objects.all():
        # items から固定フィールドに戻す
        if plan.items:
            for field_name, value in plan.items.items():
                if hasattr(plan, field_name):
                    setattr(plan, field_name, value)

        # exclusions から固定フィールドに戻す
        if plan.exclusions:
            for field_name, value in plan.exclusions.items():
                exclude_field = f'exclude_{field_name}'
                if hasattr(plan, exclude_field):
                    setattr(plan, exclude_field, value)

        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0044_add_flexible_items'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_data_to_json, reverse_migration),
    ]
