# Generated by Django 5.2.8 on 2025-12-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0045_migrate_to_flexible_items'),
    ]

    operations = [
        # まずユニーク制約なしでフィールドを追加
        migrations.AddField(
            model_name='monthlyplandefault',
            name='key',
            field=models.CharField(blank=True, default='', help_text='項目の一意識別子（自動生成）', max_length=100, verbose_name='フィールド名'),
        ),
    ]
