# Generated by Django 5.2.8 on 2025-12-28 05:08

from django.db import migrations


def populate_keys(apps, schema_editor):
    """既存のMonthlyPlanDefaultレコードにkeyを設定"""
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')
    import re

    # タイトル→キーのマッピング
    mapping = {
        '給与': 'salary',
        'ボーナス': 'bonus',
        '食費': 'food',
        '家賃': 'rent',
        'レイク': 'lake',
        'レイク返済': 'lake',
        'VIEWカード': 'view_card',
        'ボーナス払い': 'view_card_bonus',
        '楽天カード': 'rakuten_card',
        'PayPayカード': 'paypay_card',
        'VERMILLION CARD': 'vermillion_card',
        'Amazonカード': 'amazon_card',
        'Olive': 'olive_card',
        'マネーアシスト返済': 'loan',
        'マネーアシスト借入': 'loan_borrowing',
        'ジム': 'other',
        'その他': 'other',
    }

    used_keys = set()

    for item in MonthlyPlanDefault.objects.all():
        if not item.key:  # keyが空の場合のみ設定
            # マッピングから取得、なければ自動生成
            if item.title in mapping:
                base_key = mapping[item.title]
            else:
                base_key = re.sub(r'[^\w\s-]', '', item.title)
                base_key = re.sub(r'[\s-]+', '_', base_key.strip()).lower()
                if not base_key:
                    base_key = 'custom_item'

            # 一意性を確保
            key = base_key
            counter = 1
            while key in used_keys:
                key = f"{base_key}_{counter}"
                counter += 1

            item.key = key
            used_keys.add(key)
            item.save()


def reverse_populate_keys(apps, schema_editor):
    """ロールバック時にkeyをクリア"""
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')
    MonthlyPlanDefault.objects.all().update(key='')


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0046_monthlyplandefault_key'),
    ]

    operations = [
        migrations.RunPython(populate_keys, reverse_populate_keys),
    ]
