# Generated by Django 5.2.8 on 2025-12-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0047_populate_monthly_plan_default_keys'),
    ]

    operations = [
        # データ移行後にユニーク制約を追加
        migrations.AlterField(
            model_name='monthlyplandefault',
            name='key',
            field=models.CharField(
                blank=True,
                default='',
                help_text='項目の一意識別子（自動生成）',
                max_length=100,
                unique=True,
                verbose_name='フィールド名'
            ),
        ),
    ]
