# Generated by Django 5.2.8 on 2025-12-28 05:28

from django.db import migrations


def convert_keys_to_id_based(apps, schema_editor):
    """
    既存のMonthlyPlanDefaultのkeyをIDベースに変換し、
    MonthlyPlanのitemsとexclusionsを新しいkeyに更新
    """
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')
    MonthlyPlan = apps.get_model('budget_app', 'MonthlyPlan')

    # 旧key → 新key(item_{id}) のマッピングを作成
    old_to_new_key_map = {}

    for item in MonthlyPlanDefault.objects.all():
        old_key = item.key
        new_key = f'item_{item.id}'
        old_to_new_key_map[old_key] = new_key

        # MonthlyPlanDefaultのkeyを更新
        item.key = new_key
        item.save()

    # MonthlyPlanの全レコードのitemsとexclusionsを変換
    for plan in MonthlyPlan.objects.all():
        # itemsを変換
        new_items = {}
        for old_key, value in plan.items.items():
            new_key = old_to_new_key_map.get(old_key, old_key)
            new_items[new_key] = value
        plan.items = new_items

        # exclusionsを変換
        new_exclusions = {}
        for old_key, value in plan.exclusions.items():
            new_key = old_to_new_key_map.get(old_key, old_key)
            new_exclusions[new_key] = value
        plan.exclusions = new_exclusions

        plan.save()


def reverse_conversion(apps, schema_editor):
    """ロールバック用（元のkeyに戻す）"""
    # ロールバックは複雑なので、実装しない
    # もし必要なら手動でデータベースをバックアップから復元
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0048_add_unique_constraint_to_key'),
    ]

    operations = [
        migrations.RunPython(convert_keys_to_id_based, reverse_conversion),
    ]
