# Generated by Django 5.2.8 on 2025-12-28 09:34

from django.db import migrations


def fix_bonus_payment_closing_day(apps, schema_editor):
    """ボーナス払い項目にis_end_of_month=Trueを設定"""
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')

    # ボーナス払い項目を取得
    bonus_items = MonthlyPlanDefault.objects.filter(title__contains='ボーナス払い')

    # is_end_of_month を True に設定
    for item in bonus_items:
        item.is_end_of_month = True
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0049_convert_keys_to_id_based'),
    ]

    operations = [
        migrations.RunPython(fix_bonus_payment_closing_day),
    ]
