# Generated by Django 5.2.8 on 2025-12-28 10:15

from django.db import migrations


def migrate_legacy_to_items(apps, schema_editor):
    """古いフィールドのデータをitems JSONFieldに移行"""
    MonthlyPlan = apps.get_model('budget_app', 'MonthlyPlan')
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')

    # migration 0049で変換されたkeyと古いフィールド名のマッピング
    legacy_field_mapping = {
        'item_1': 'food',
        'item_2': 'rent',
        'item_3': 'lake',
        'item_12': 'view_card',
        'item_13': 'view_card_bonus',
        'item_14': 'rakuten_card',
        'item_15': 'paypay_card',
        'item_16': 'vermillion_card',
        'item_17': 'amazon_card',
        'item_18': 'olive_card',
        'item_20': 'loan_borrowing',
    }

    # 全てのMonthlyPlanを取得
    for plan in MonthlyPlan.objects.all():
        # itemsが辞書でない場合は初期化
        if not isinstance(plan.items, dict):
            plan.items = {}

        # 各マッピングについて、古いフィールドにデータがあればitemsにコピー
        for new_key, old_field in legacy_field_mapping.items():
            old_value = getattr(plan, old_field, 0)
            if old_value != 0:
                # 新しいkeyに値がない、または0の場合のみコピー
                if new_key not in plan.items or plan.items[new_key] == 0:
                    plan.items[new_key] = old_value

        # exclusionsの移行
        if not isinstance(plan.exclusions, dict):
            plan.exclusions = {}

        exclude_mapping = {
            'item_12': 'exclude_view_card',
            'item_13': 'exclude_view_card_bonus',
            'item_14': 'exclude_rakuten_card',
            'item_15': 'exclude_paypay_card',
            'item_16': 'exclude_vermillion_card',
            'item_17': 'exclude_amazon_card',
            'item_18': 'exclude_olive_card',
        }

        for new_key, old_field in exclude_mapping.items():
            old_value = getattr(plan, old_field, False)
            if old_value:
                if new_key not in plan.exclusions:
                    plan.exclusions[new_key] = old_value

        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0050_fix_bonus_payment_is_end_of_month'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_to_items),
    ]
