# Generated by Django 5.2.8 on 2025-12-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0051_migrate_legacy_fields_to_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplandefault',
            name='depends_on_key',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=100,
                verbose_name="依存する項目のkey",
                help_text="この項目が表示される条件として、指定されたkeyの項目に値がある必要がある"
            ),
        ),
        migrations.AddField(
            model_name='monthlyplandefault',
            name='offset_months',
            field=models.IntegerField(
                default=0,
                verbose_name="表示月オフセット",
                help_text="depends_on_keyで指定された項目から何ヶ月後に表示するか（例：1=翌月、0=同月）"
            ),
        ),
    ]
