# Generated by Django 5.2.8 on 2025-12-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0052_add_conditional_display_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, unique=True, verbose_name='年月')),
                ('gross_salary', models.IntegerField(default=0, verbose_name='総支給額')),
                ('deductions', models.IntegerField(default=0, verbose_name='控除額')),
                ('transportation', models.IntegerField(default=0, verbose_name='交通費')),
                ('has_bonus', models.BooleanField(default=False, verbose_name='ボーナスあり')),
                ('bonus_gross_salary', models.IntegerField(default=0, verbose_name='ボーナス総支給額')),
                ('bonus_deductions', models.IntegerField(default=0, verbose_name='ボーナス控除額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '給与明細',
                'verbose_name_plural': '給与明細',
                'ordering': ['year_month'],
            },
        ),
    ]
