# Generated by Django 5.2.8 on 2025-12-29 12:33

from django.db import migrations


def migrate_salary_data(apps, schema_editor):
    """既存のMonthlyPlanデータからSalaryモデルにデータをコピー"""
    MonthlyPlan = apps.get_model('budget_app', 'MonthlyPlan')
    Salary = apps.get_model('budget_app', 'Salary')

    for plan in MonthlyPlan.objects.all():
        # 給与明細データまたはボーナス明細データがある場合のみSalaryを作成
        if (plan.gross_salary > 0 or plan.deductions > 0 or plan.transportation > 0 or
            plan.bonus_gross_salary > 0 or plan.bonus_deductions > 0):

            # has_bonusは、ボーナス総支給額またはボーナス控除額がある場合にTrue
            has_bonus = plan.bonus_gross_salary > 0 or plan.bonus_deductions > 0

            Salary.objects.create(
                year_month=plan.year_month,
                gross_salary=plan.gross_salary,
                deductions=plan.deductions,
                transportation=plan.transportation,
                has_bonus=has_bonus,
                bonus_gross_salary=plan.bonus_gross_salary,
                bonus_deductions=plan.bonus_deductions,
            )


def reverse_migrate(apps, schema_editor):
    """ロールバック時は全Salaryデータを削除"""
    Salary = apps.get_model('budget_app', 'Salary')
    Salary.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0053_salary'),
    ]

    operations = [
        migrations.RunPython(migrate_salary_data, reverse_migrate),
    ]
