# Generated by Django 5.2.8 on 2025-12-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0054_migrate_salary_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplandefault',
            name='card_id',
            field=models.CharField(blank=True, help_text='クレジットカード項目の一意識別子（自動生成: card_1, card_2, ...）', max_length=50, null=True, unique=True, verbose_name='カードID'),
        ),
        migrations.AddField(
            model_name='monthlyplandefault',
            name='is_bonus_payment',
            field=models.BooleanField(default=False, help_text='ボーナス払い用の項目かどうか', verbose_name='ボーナス払い'),
        ),
        migrations.AlterField(
            model_name='creditestimate',
            name='card_type',
            field=models.CharField(max_length=50, verbose_name='カード'),
        ),
    ]
