# Generated by Django 5.2.8 on 2025-12-30 09:33

from django.db import migrations


def populate_card_id(apps, schema_editor):
    """既存のクレジットカード項目にcard_idとis_bonus_paymentを設定"""
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')

    # 全てのMonthlyPlanDefaultを取得
    for item in MonthlyPlanDefault.objects.all():
        # クレジットカード項目かチェック（締め日が設定されているもの）
        is_credit_card = item.closing_day is not None or item.is_end_of_month

        if is_credit_card:
            # card_idを自動生成
            if not item.card_id:
                item.card_id = f'card_{item.pk}'

            # is_bonus_paymentを設定（タイトルに「ボーナス」が含まれるか）
            item.is_bonus_payment = 'ボーナス' in item.title

            item.save()


def reverse_populate(apps, schema_editor):
    """ロールバック時にcard_idとis_bonus_paymentをクリア"""
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')
    MonthlyPlanDefault.objects.all().update(card_id=None, is_bonus_payment=False)


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0055_monthlyplandefault_card_id_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_card_id, reverse_populate),
    ]
