# Generated by Django 5.2.8 on 2025-12-30 12:00

from django.db import migrations


def migrate_card_types(apps, schema_editor):
    """CreditDefaultとDefaultChargeOverrideのcard_typeを新形式に移行"""
    CreditDefault = apps.get_model('budget_app', 'CreditDefault')
    DefaultChargeOverride = apps.get_model('budget_app', 'DefaultChargeOverride')

    # 古いカード名から新しいcard_idへのマッピング
    card_type_mapping = {
        'view': 'card_12',
        'view_bonus': 'card_13',
        'rakuten': 'card_14',
        'paypay': 'card_15',
        'vermillion': 'card_16',
        'amazon': 'card_17',  # Amazonカードが存在する場合
        'olive': 'card_18',
    }

    # CreditDefaultを更新
    for default in CreditDefault.objects.all():
        old_card_type = default.card_type
        if old_card_type in card_type_mapping:
            new_card_type = card_type_mapping[old_card_type]
            default.card_type = new_card_type
            default.save()
            print(f'CreditDefault ID {default.pk}: {old_card_type} -> {new_card_type}')

    # DefaultChargeOverrideを更新
    for override in DefaultChargeOverride.objects.all():
        old_card_type = override.card_type
        if old_card_type and old_card_type in card_type_mapping:
            new_card_type = card_type_mapping[old_card_type]
            override.card_type = new_card_type
            override.save()
            print(f'DefaultChargeOverride ID {override.pk}: {old_card_type} -> {new_card_type}')


def reverse_migration(apps, schema_editor):
    """ロールバック用: 新形式から旧形式に戻す"""
    CreditDefault = apps.get_model('budget_app', 'CreditDefault')
    DefaultChargeOverride = apps.get_model('budget_app', 'DefaultChargeOverride')

    # 逆マッピング
    reverse_mapping = {
        'card_12': 'view',
        'card_13': 'view_bonus',
        'card_14': 'rakuten',
        'card_15': 'paypay',
        'card_16': 'vermillion',
        'card_17': 'amazon',
        'card_18': 'olive',
    }

    for default in CreditDefault.objects.all():
        if default.card_type in reverse_mapping:
            default.card_type = reverse_mapping[default.card_type]
            default.save()

    for override in DefaultChargeOverride.objects.all():
        if override.card_type and override.card_type in reverse_mapping:
            override.card_type = reverse_mapping[override.card_type]
            override.save()


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0056_populate_card_id'),
    ]

    operations = [
        migrations.RunPython(migrate_card_types, reverse_migration),
    ]
