# Generated by Django 5.2.8 on 2025-12-30 10:13

from django.db import migrations


def populate_offset_months(apps, schema_editor):
    """クレジットカードのoffset_monthsを設定"""
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')

    # カードごとのoffset_months設定
    # card_id -> offset_months のマッピング
    offset_mapping = {
        'card_12': 2,  # VIEWカード (1/5支払) = 翌々月
        'card_13': 0,  # VIEWカード (ボーナス払い) = due_dateで管理、offsetは使わない
        'card_14': 1,  # 楽天カード = 翌月
        'card_15': 1,  # PayPayカード = 翌月
        'card_16': 2,  # VERMILLION CARD = 翌々月
        'card_18': 1,  # Olive = 翌月
    }

    for item in MonthlyPlanDefault.objects.filter(card_id__isnull=False):
        if item.card_id in offset_mapping:
            item.offset_months = offset_mapping[item.card_id]
            item.save()
            print(f'Updated {item.card_id} ({item.title}): offset_months = {item.offset_months}')


def reverse_populate(apps, schema_editor):
    """ロールバック: offset_monthsを0に戻す"""
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')
    MonthlyPlanDefault.objects.filter(card_id__isnull=False).update(offset_months=0)


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0057_migrate_credit_default_card_type'),
    ]

    operations = [
        migrations.RunPython(populate_offset_months, reverse_populate),
    ]
