# Generated by Django 5.2.8 on 2025-12-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0058_populate_offset_months'),
    ]

    operations = [
        # Remove legacy item amount fields (now using items JSONField)
        migrations.RemoveField(model_name='monthlyplan', name='salary'),
        migrations.RemoveField(model_name='monthlyplan', name='bonus'),
        migrations.RemoveField(model_name='monthlyplan', name='food'),
        migrations.RemoveField(model_name='monthlyplan', name='rent'),
        migrations.RemoveField(model_name='monthlyplan', name='lake'),
        migrations.RemoveField(model_name='monthlyplan', name='view_card'),
        migrations.RemoveField(model_name='monthlyplan', name='view_card_bonus'),
        migrations.RemoveField(model_name='monthlyplan', name='rakuten_card'),
        migrations.RemoveField(model_name='monthlyplan', name='paypay_card'),
        migrations.RemoveField(model_name='monthlyplan', name='vermillion_card'),
        migrations.RemoveField(model_name='monthlyplan', name='amazon_card'),
        migrations.RemoveField(model_name='monthlyplan', name='olive_card'),
        migrations.RemoveField(model_name='monthlyplan', name='savings'),
        migrations.RemoveField(model_name='monthlyplan', name='loan'),
        migrations.RemoveField(model_name='monthlyplan', name='loan_borrowing'),
        migrations.RemoveField(model_name='monthlyplan', name='other'),

        # Remove legacy exclusion fields (now using exclusions JSONField)
        migrations.RemoveField(model_name='monthlyplan', name='exclude_view_card'),
        migrations.RemoveField(model_name='monthlyplan', name='exclude_view_card_bonus'),
        migrations.RemoveField(model_name='monthlyplan', name='exclude_rakuten_card'),
        migrations.RemoveField(model_name='monthlyplan', name='exclude_paypay_card'),
        migrations.RemoveField(model_name='monthlyplan', name='exclude_vermillion_card'),
        migrations.RemoveField(model_name='monthlyplan', name='exclude_amazon_card'),
        migrations.RemoveField(model_name='monthlyplan', name='exclude_olive_card'),
    ]
