# Generated by Django 5.2.8 on 2025-12-30 11:21

from django.db import migrations


def renumber_item_keys(apps, schema_editor):
    """
    MonthlyPlanDefaultのkeyをitem_1から順番に振り直す
    同時にMonthlyPlanのitemsとexclusionsのキーも更新する
    """
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')
    MonthlyPlan = apps.get_model('budget_app', 'MonthlyPlan')

    # 現在のitem_XXから新しいitem_XXへのマッピングを作成
    old_to_new_mapping = {}

    # IDの順番でitem_1から順に振り直す
    defaults = MonthlyPlanDefault.objects.all().order_by('id')
    for index, item in enumerate(defaults, start=1):
        old_key = item.key
        new_key = f'item_{index}'
        old_to_new_mapping[old_key] = new_key

        # MonthlyPlanDefaultのkeyを更新
        item.key = new_key
        item.save()

    # MonthlyPlanのitemsとexclusionsのキーを更新
    for plan in MonthlyPlan.objects.all():
        # itemsを更新
        if plan.items:
            new_items = {}
            for old_key, value in plan.items.items():
                new_key = old_to_new_mapping.get(old_key, old_key)
                new_items[new_key] = value
            plan.items = new_items

        # exclusionsを更新
        if plan.exclusions:
            new_exclusions = {}
            for old_key, value in plan.exclusions.items():
                new_key = old_to_new_mapping.get(old_key, old_key)
                new_exclusions[new_key] = value
            plan.exclusions = new_exclusions

        plan.save()


def reverse_renumber(apps, schema_editor):
    """Reverse migration is not supported"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0059_remove_legacy_fields'),
    ]

    operations = [
        migrations.RunPython(renumber_item_keys, reverse_renumber),
    ]
