# Generated by Django 5.2.8 on 2025-12-30 11:24

from django.db import migrations


def update_card_types(apps, schema_editor):
    """
    CreditEstimateとCreditDefaultのcard_typeを新しいitem番号に更新
    旧card_XX形式および古いカード名から新しいitem_XX形式に変換

    card_typeはMonthlyPlanDefaultのkeyと完全に統一される。
    card_という接頭辞は使わず、直接item_6, item_7のように
    MonthlyPlanDefaultのkeyと同じ値を使用する。
    """
    CreditEstimate = apps.get_model('budget_app', 'CreditEstimate')
    CreditDefault = apps.get_model('budget_app', 'CreditDefault')
    DefaultChargeOverride = apps.get_model('budget_app', 'DefaultChargeOverride')

    # 古いcard_type → 新しいitem_key のマッピング
    # MonthlyPlanDefaultのkeyと完全に統一（card_接頭辞は使わない）
    card_mapping = {
        # 古いcard_XX形式
        'card_12': 'item_6',   # VIEWカード (ID 12)
        'card_13': 'item_7',   # VIEWカード (ボーナス払い) (ID 13)
        'card_14': 'item_8',   # 楽天カード (ID 14)
        'card_15': 'item_9',   # PayPayカード (ID 15)
        'card_16': 'item_10',  # VERMILLION CARD (ID 16)
        'card_17': 'item_11',  # Amazonカード (ID 17)
        'card_18': 'item_12',  # Olive (ID 18)
        # 古いカード名形式（もし残っていれば）
        'view': 'item_6',
        'view_bonus': 'item_7',
        'rakuten': 'item_8',
        'paypay': 'item_9',
        'vermillion': 'item_10',
        'amazon': 'item_11',
        'olive': 'item_12',
    }

    # CreditEstimateを更新
    for estimate in CreditEstimate.objects.all():
        old_type = estimate.card_type
        if old_type in card_mapping:
            estimate.card_type = card_mapping[old_type]
            estimate.save()

    # CreditDefaultを更新
    for default in CreditDefault.objects.all():
        old_type = default.card_type
        if old_type in card_mapping:
            default.card_type = card_mapping[old_type]
            default.save()

    # DefaultChargeOverrideを更新
    for override in DefaultChargeOverride.objects.all():
        if override.card_type:
            old_type = override.card_type
            if old_type in card_mapping:
                override.card_type = card_mapping[old_type]
                override.save()


def reverse_update(apps, schema_editor):
    """Reverse migration is not supported"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0060_renumber_item_keys'),
    ]

    operations = [
        migrations.RunPython(update_card_types, reverse_update),
    ]
