# Generated by Django 5.2.8 on 2025-12-30 15:01

from django.db import migrations


def reset_ids(apps, schema_editor):
    """Reset MonthlyPlanDefault IDs to start from 1"""
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')

    # Get all items ordered by current ID
    items = list(MonthlyPlanDefault.objects.all().order_by('id'))

    if not items:
        return

    # Create a mapping of old IDs to new IDs
    id_mapping = {}
    for new_id, item in enumerate(items, start=1):
        id_mapping[item.id] = new_id

    # Update card_id fields to use new ID format
    for item in items:
        if item.card_id:
            # Extract the numeric part from card_XX format
            old_num = item.card_id.replace('card_', '')
            if old_num.isdigit():
                new_num = id_mapping.get(int(old_num))
                if new_num:
                    item.card_id = f'item_{new_num}'

    # Delete all existing items
    MonthlyPlanDefault.objects.all().delete()

    # Reset the sequence (PostgreSQL)
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("ALTER SEQUENCE budget_app_monthlyplandefault_id_seq RESTART WITH 1")

    # Re-create items with new IDs
    for new_id, item in enumerate(items, start=1):
        item.id = new_id
        item.save()


def reverse_reset(apps, schema_editor):
    """This migration cannot be reversed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0061_update_credit_card_types'),
    ]

    operations = [
        migrations.RunPython(reset_ids, reverse_reset),
    ]
