# Generated by Django 4.2.26 on 2026-01-08 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0062_reset_monthly_plan_default_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdefault',
            name='payment_day',
            field=models.IntegerField(default=1, help_text='1-31の数値。毎月この日に自動生成されます（例: Netflix = 1日）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(31)], verbose_name='毎月の利用日'),
        ),
        migrations.AlterField(
            model_name='creditdefault',
            name='card_type',
            field=models.CharField(max_length=50, verbose_name='カード種別'),
        ),
    ]
