# Generated by Django 5.2.8 on 2026-01-08

from django.db import migrations


def fix_vermillion_card_settings(apps, schema_editor):
    """
    VERMILLIONカードの設定を修正
    - closing_day: None → 10 (10日締め)
    - offset_months: 0 → 1 (利用月の翌月に支払い)

    例: 1/11～2/10利用 → 2/10締め → 3/4支払い
    """
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')

    vermillion_card = MonthlyPlanDefault.objects.filter(key='item_7').first()
    if vermillion_card:
        vermillion_card.closing_day = 10
        vermillion_card.offset_months = 1
        vermillion_card.save()
        print(f"Updated VERMILLION card: closing_day=10, offset_months=1")


def reverse_vermillion_card_settings(apps, schema_editor):
    """設定を元に戻す"""
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')

    vermillion_card = MonthlyPlanDefault.objects.filter(key='item_7').first()
    if vermillion_card:
        vermillion_card.closing_day = None
        vermillion_card.offset_months = 0
        vermillion_card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0063_creditdefault_payment_day_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_vermillion_card_settings, reverse_vermillion_card_settings),
    ]
