# Generated by Django 5.2.8 on 2026-01-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0065_fix_view_and_vermillion_card_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultchargeoverride',
            name='purchase_date_override',
            field=models.DateField(blank=True, help_text='この月だけ利用日を変更する場合に指定', null=True, verbose_name='利用日上書き'),
        ),
        migrations.AlterField(
            model_name='monthlyplandefault',
            name='is_withdrawal_end_of_month',
            field=models.BooleanField(default=False, help_text='チェックすると引落日 / 振込日が月末になります', verbose_name='引落日 / 振込日を月末にする'),
        ),
        migrations.AlterField(
            model_name='monthlyplandefault',
            name='withdrawal_day',
            field=models.IntegerField(blank=True, help_text='1-31の数値。引落日または振込日を設定', null=True, verbose_name='引落日 / 振込日'),
        ),
    ]
