# Generated by Django 4.2.26 on 2026-01-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0066_defaultchargeoverride_purchase_date_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplan',
            name='temporary_items',
            field=models.JSONField(default=list, help_text="臨時収入・支出のリスト 例: [{'name': '旅行', 'amount': -50000, 'date': 15, 'type': 'expense'}]", verbose_name='臨時項目'),
        ),
    ]
