# Generated by Django 5.2.8 on 2026-02-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0067_add_temporary_items_to_monthly_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdefault',
            name='is_usd',
            field=models.BooleanField(default=False, verbose_name='ドル入力'),
        ),
        migrations.AddField(
            model_name='creditdefault',
            name='usd_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='金額（ドル）'),
        ),
        migrations.AddField(
            model_name='creditestimate',
            name='is_usd',
            field=models.BooleanField(default=False, verbose_name='ドル入力'),
        ),
        migrations.AddField(
            model_name='creditestimate',
            name='usd_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='金額（ドル）'),
        ),
        migrations.AddField(
            model_name='defaultchargeoverride',
            name='is_usd',
            field=models.BooleanField(default=False, verbose_name='ドル入力'),
        ),
        migrations.AddField(
            model_name='defaultchargeoverride',
            name='usd_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='金額（ドル）'),
        ),
    ]
