# Generated by Django 5.2.8 on 2026-02-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0068_creditdefault_is_usd_creditdefault_usd_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationconfig',
            name='savings_day',
            field=models.IntegerField(default=26, help_text='毎月何日に定期預金が引き落とされるか（1〜28）', verbose_name='定期預金引き落とし日'),
        ),
    ]
