# Generated by Django 5.2.8 on 2026-02-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0069_add_savings_day_to_simulationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationconfig',
            name='savings_day',
            field=models.IntegerField(blank=True, help_text='毎月何日に定期預金が引き落とされるか（1〜28）', null=True, verbose_name='定期預金引き落とし日'),
        ),
    ]
