# Generated by Django 4.2.28 on 2026-03-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0070_savings_day_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationconfig',
            name='balance_set_date',
            field=models.DateField(blank=True, help_text='現在残高を最後に手動設定した日付', null=True, verbose_name='残高設定日'),
        ),
    ]
