# Generated by Django 4.2.28 on 2026-04-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0071_add_balance_set_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditestimate',
            name='bonus_payment_type',
            field=models.CharField(blank=True, choices=[('bic_camera', 'ビックカメラ'), ('standard', 'スタンダード')], default='', max_length=20, verbose_name='ボーナス払い種別'),
        ),
    ]
