# Generated by Django 4.2.28 on 2026-04-24

from django.db import migrations, models


def setup_bonus_payment_types(apps, schema_editor):
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')

    # item_7 (既存のビックカメラ) を bic_camera に設定し、タイトルを更新
    MonthlyPlanDefault.objects.filter(key='item_7', is_bonus_payment=True).update(
        bonus_payment_type='bic_camera',
        title='VIEWカード【ビックカメラボーナス払い】',
    )

    try:
        item_7 = MonthlyPlanDefault.objects.get(key='item_7', is_bonus_payment=True)
    except MonthlyPlanDefault.DoesNotExist:
        return

    # スタンダード用エントリがなければ作成
    if MonthlyPlanDefault.objects.filter(is_bonus_payment=True, bonus_payment_type='standard').exists():
        return

    std = MonthlyPlanDefault.objects.create(
        title='VIEWカード【スタンダードボーナス払い】',
        key='temp_standard',
        amount=0,
        payment_type=item_7.payment_type,
        withdrawal_day=item_7.withdrawal_day,
        is_withdrawal_end_of_month=item_7.is_withdrawal_end_of_month,
        consider_holidays=item_7.consider_holidays,
        closing_day=item_7.closing_day,
        is_end_of_month=item_7.is_end_of_month,
        is_active=True,
        order=item_7.order + 1,
        is_bonus_payment=True,
        bonus_payment_type='standard',
    )
    MonthlyPlanDefault.objects.filter(pk=std.pk).update(
        key=f'item_{std.pk}',
        card_id=f'card_{std.pk}',
    )


def reverse_setup(apps, schema_editor):
    MonthlyPlanDefault = apps.get_model('budget_app', 'MonthlyPlanDefault')
    MonthlyPlanDefault.objects.filter(is_bonus_payment=True, bonus_payment_type='standard').delete()
    MonthlyPlanDefault.objects.filter(key='item_7').update(
        bonus_payment_type='',
        title='VIEWカード【ボーナス払い】',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0072_add_bonus_payment_type_to_credit_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyplandefault',
            name='bonus_payment_type',
            field=models.CharField(blank=True, choices=[('bic_camera', 'ビックカメラ'), ('standard', 'スタンダード')], default='', max_length=20, verbose_name='ボーナス払い種別'),
        ),
        migrations.RunPython(setup_bonus_payment_types, reverse_setup),
    ]
